### ISSUE TITLE
CRITICAL ISSUE: RTCBundlePolicy / RTCOfferOptions Not Working

### ISSUE THREAD

**Issue by theDude30** [SamsungInternet/support#10]
Hi,
I'm utilizing the twillio webRTC video component and it works great on all android chrome phones except for samsung internet.
The app.rtc example from google works in the samsung internet but the the webRTC twillio does not.
The twillio team identified that RTCBundlePolicy / RTCOfferOptions are not supported in samsung internet.
Our Audio/Video component is officially released and some clients are complaining about this issue.
For more details: See below the issue i posted in the twillio's github
twilio/twilio-video.js#112
Can you please provide more information or help in finding a workaround for this issue?

Thanks.

**Comment by poshaughnessy** [comment]
Thank you for reporting this, @theDude30.

Please could you confirm which version of Samsung Internet you have observed this in?

Also might you have any test case to hand that we could use to replicate it?

We will share this with our engineering colleagues and be sure to follow up.

**Comment by theDude30** [comment]
I've saw that on 5.0.30-40 version.
I don't have a test case that i can provide for you to replicate the problem.
I suggest you contact the twilio development team and they would be able to provide much better details and some test case (https://github.com/twilio/twilio-video.js/issues/112)

**Comment by poshaughnessy** [comment]
Thanks @theDude30. I'm following up with Twilio. We'll try to get this figured out.

**Comment by theDude30** [comment]
Is there an update on this issue?

**Comment by markandrus** [comment]
If I'm not mistaken, Samsung Internet is currently built from Chromium M51. Chromium M51 has [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=619289) surrounding the use of `offerToReceiveAudio` and `offerToReceiveVideo` in the Promise-returning `createOffer` API. There is a workaround [here](https://github.com/webrtc/adapter/blob/421dffb635726a5486f178f8c023da60cc7edd4a/src/js/chrome/chrome_shim.js#L401) in webrtc/adapter.

**Comment by poshaughnessy** [comment]
Thanks @markandrus, yes Samsung Internet v5 is based on Chromium M51. We should have another major release later this year v6 which will upgrade the Chromium engine.

**Comment by poshaughnessy** [comment]
@theDude30 Please might you be able to check in our v6 update? (Beta available here: https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser.beta)

**Comment by poshaughnessy** [comment]
I think this should be resolved in our v6 [which is now being released](https://medium.com/samsung-internet-dev/samsung-internet-v6-2-now-stable-ab7f95ed8b4b). So I'll close this. But if it's still a problem, please comment and we can re-open.
