### ISSUE TITLE
Enable bottom bar and action button menu in Samsung Internet Custom Tabs.

### ISSUE THREAD

**Issue by arunkumar9t2** [SamsungInternet/support#11]
I am the developer of an app called [Chromer](https://github.com/arunkumar9t2/chromer) which is a browser app that uses Custom Tabs internally to render pages. On top of Custom Tab, I provide options like floating bubbles etc.

Samsung Internet also provides Custom Tabs but there are some missing changes from Chromium here. For example, 

- Samsung Internet does not honor setting an ActionButton in the toolbar by calling `CustomTabsIntent#setActionButton`. Refer relevant [code](https://github.com/GoogleChrome/custom-tabs-client/blob/master/customtabs/src/android/support/customtabs/CustomTabsIntent.java#L399).

- Samsung Internet does not honor setting a `RemoteView` for bottom bar. 
Relevant [code](https://github.com/GoogleChrome/custom-tabs-client/blob/master/customtabs/src/android/support/customtabs/CustomTabsIntent.java#L465).

It would great if these changes could be implemented. I am attaching links to Chromium project which could be helpful.

- [BottomBar](https://chromium.googlesource.com/chromium/src/+/60.0.3110.2/chrome/android/java/src/org/chromium/chrome/browser/customtabs/CustomTabBottomBarDelegate.java)

**Comment by poshaughnessy** [comment]
Sorry for the slow reply @arunkumar9t2 (I've been away the last couple of weeks) - thanks for raising this. I'll try to find out the status on these features for Custom Tabs and let you know once I have some info to share.

**Comment by arunkumar9t2** [comment]
Hi, I found that Samsung Internet now supports bottom bar. Thank you! Closing the issue.
