### ISSUE TITLE
No Pointer Lock API support

### ISSUE THREAD

**Issue by Muvkina** [SamsungInternet/support#110]
When trying any websites that use pointer lock api the mouse is not captured at all.

**Comment by AdaRoseCannon** [comment]
We don't really use this repo any more best to email ***@***.***

Out of curiosity is this in DeX or a mouse plugged into the phone/tablet?

**Comment by Muvkina** [comment]
It doesn't work on dex or outside of dex also I'm not sure if it's something on my side but the email didn't show up at all

**Comment by Muvkina** [comment]
I just saw the readme I opened a topic on samsung internet developer forums I hope that was the right place

**Comment by AdaRoseCannon** [comment]
Yeah it is
