### ISSUE TITLE
old Web engine version

### ISSUE THREAD

**Issue by theDude30** [SamsungInternet/support#13]
Hi,
I noticed that the samsung internet browser is using old version of chromium.
When are you planing to update the web engine version?

**Comment by AdaRoseEdwards** [comment]
We upgrade the core engine version every major release:

4 -> Chrome 44
5 -> Chrome 51

I can't confirm a date for version 6

**Comment by poshaughnessy** [comment]
@theDude30 We're planning to upgrade the Chromium engine again with v6. As Ada said, we can't confirm a date for that right now, any more specifically than "second half of this year". We'll be sure to announce as loudly as we can, when we can, though.

**Comment by poshaughnessy** [comment]
@theDude30 p.s. Sorry forgot to say - we'll have a beta version out before the next major release again, so that will give us a chance to check any issues in advance.

**Comment by DaSchTour** [comment]
I heard rumors about Samsung Internet 6 using Chromium 56 which is the last version that doesn't support CSS grid. Current support for CSS Grid in Europe and North America is at over 80%. With iOS 11 I thought we would reach 90% by the end of this year. But I guess the last 5% missing will be Samsung Internet 😞

**Comment by poshaughnessy** [comment]
@DaSchTour Don't worry, we know how important CSS Grid is so we've backported it in from 57.

**Comment by DaSchTour** [comment]
@poshaughnessy okay, that's great news 😄 thx
