### ISSUE TITLE
Unable to decode WebM Opus audio in Samsung Internet 5.4, breaks all Construct 3 content

### ISSUE THREAD

**Issue by AshleyScirra** [SamsungInternet/support#14]
Using Samsung Internet 5.4.00-75 on a Samsung Galaxy S8.

Repro URL: https://www.scirra.com/labs/webmopustest/

The demo page displays the result of `new Audio().canPlayType("audio/webm; codecs=opus")`, which returns "probably" in both Samsung Internet and Chrome. (According to the spec, this is the most optimistic result, i.e. "yes, it's supported").

However if you actually decode a WebM Opus file, Samsung Internet fails with `EncodingError`, whereas Chrome successfully decodes the file.

This breaks all content built with [Construct 3](https://editor.construct.net), because it prefers to load WebM Opus if the browser indicates it is supported, but the actual decoding fails. Users [have noticed and reported this to us](https://github.com/Scirra/Construct-3-bugs/issues/605).

If Samsung Internet does not support WebM Opus, the `canPlayType` call should return an empty string (as browsers like Edge do). This will prevent Construct 3 trying to decode the file. If Samsung Internet returns "probably" for the `canPlayType` call, then decoding a WebM Opus file should actually succeed, as it does in Chrome.

**Comment by AshleyScirra** [comment]
Still reproduces in 5.4.02.3

**Comment by poshaughnessy** [comment]
@AshleyScirra Sorry for our slowness picking up on this! v6.0 has just started shipping now, initially on the Galaxy Note 8 (as per our usual process: https://poshaughnessy.github.io/mighty-morphin-browser-strangers-sotb-2017/#66). I can't give an exact date, but the stable v6.2 will get released for all supported devices shortly.

**Comment by poshaughnessy** [comment]
@AshleyScirra p.s. We were just both at SOTB6 weren't we! I understand now the irony that I talked about opening up our Github support repo in my talk, and at the top of the screenshot it showed your unanswered issue! 😨😳 I will try to do better! Also please feel free to chase us up on Twitter @poshaughnessy @samsunginternet if you need us.

**Comment by AshleyScirra** [comment]
Haha it's ok, I was pretty worried about this originally but if the fixed version is going out soon then I think it's fine! Construct 3 is still in beta so we haven't fully launched ourselves yet. Also it's quite possible this was an issue with Chromium itself that was patched fairly recently (I remember seeing something about enabling WebM Opus for decodeAudioData this year). This is a bit of a trap though if Samsung Internet is always a few versions behind Chrome - it's easy to assume it's all sorted when other Chromia take longer to catch up.

**Comment by poshaughnessy** [comment]
Hi @AshleyScirra. Our v6.2 is [now being released](https://medium.com/samsung-internet-dev/samsung-internet-v6-2-now-stable-ab7f95ed8b4b) (it should be there for most people now, although AFAIK the rollout may still take a little longer to complete as we increase the coverage gradually). Hopefully that means it's OK for us to close this issue, but if you still spot a problem, please do let me know and we can re-open this and chase it up. Thanks!
