### ISSUE TITLE
theme-color meta tag text colour

### ISSUE THREAD

**Issue by AverageMarcus** [SamsungInternet/support#15]
Version: 6.2.00.38

When using some light colour for the `theme-color` meta tag such as `#f7df1e` (JS Yellow) the text colour is set to white, causing the URL and icons to be hard to see. The same page in Chrome for Android renders with black text.

Example page: http://output.jsbin.com/pubedewuri

E.g.
**Samsung Internet**
![image](https://user-images.githubusercontent.com/3384072/30785627-a6c676f8-a161-11e7-9c8c-46c3e978f598.png)

**Chrome for Android**
![image](https://user-images.githubusercontent.com/3384072/30785630-b2b37ef2-a161-11e7-88f7-5785e972ce36.png)

I have also seen this on some light greys and similar colours. 

Ideally, for any colour specified in the `theme-color` meta tag, the rendered text colour should pass the WCAG AA colour contrast test.

**Comment by poshaughnessy** [comment]
Thank you for reporting this @AverageMarcus and sorry for the slow reply, I've mentioned this briefly to our HQ colleagues already and it's [Chuseok](https://en.wikipedia.org/wiki/Chuseok) this week but I'll follow up again soon!

NB. The live preview of the JSBin has expired, so I recreated it here:

https://poshaughnessy.github.io/theme-color-meta-tag-test/
https://github.com/poshaughnessy/theme-color-meta-tag-test

**Comment by AverageMarcus** [comment]
Ah! Didn't realise I wasn't logged in to JSBin. Thanks to recreating!

**Comment by poshaughnessy** [comment]
Hi again @AverageMarcus, just for the record, to let you know this has been raised internally too.

**Comment by poshaughnessy** [comment]
We've been informed that this has been resolved now, so should go out in a future release soon. I'll close this to keep our open issues list to unresolved items, but if I hear of the release date for it I'll comment with further info then. Thanks again for raising!

**Comment by poshaughnessy** [comment]
Hi @AverageMarcus. I think this is resolved now? I can see black text now, with both v6.4 and v7.2 Beta (screenshots below). If you still spot an issue though, please LMK!

v6.4

<img src="https://user-images.githubusercontent.com/151207/38085030-fa9ea3b4-3346-11e8-9201-cb560e2703d0.png" width="300px"/>

v7.2 Beta

<img src="https://user-images.githubusercontent.com/151207/38085038-00526c82-3347-11e8-8a10-d9d2194fe571.png" width="300px"/>
