### ISSUE TITLE
support Android Intents for deep-linking URLs in Samsung Internet Browser on Gear VR

### ISSUE THREAD

**Issue by cvan** [SamsungInternet/support#16]
It would be nice to have Android Intents supported in Samsung Internet Browser.

My specific use case is I want a user on 2D mobile be able to click the "Enter VR" button on an A-Frame WebVR site, and have that trigger opening the Samsung Internet Browser in Gear VR mode.

In order to intercept that click, an Android Intent would need to be registered for the Samsung Internet Browser Android app, as well as a JavaScript protocol (`intent://`):

```html
<a href="intent://#Intent;package=com.samsung.browser;S.uri=https://aframe.io/aframe/examples/showcase/spheres-and-fog/;end">Enter VR</a>
```

[Here are the docs for **Android Intents with Chrome**](https://developer.chrome.com/multidevice/android/intents), which works today in Chrome for Android.

<hr>

See the discussion in this Twitter thread: https://twitter.com/cvanw/status/910428329114689536

<hr>

Related reading:
- https://paul.kinlan.me/sharing-natively-on-android-from-the-web/
- https://paul.kinlan.me/every-browser-should-support-intent-urls/

**Comment by AdaRoseEdwards** [comment]
To open the GearVR browser specifically the intent should probably be something like: `intent://#Intent;package=com.sec.android.app.svrbrowser;S.uri=https://aframe.io/aframe/examples/showcase/spheres-and-fog/;end`

We are going to take a look into this.

**Comment by cvan** [comment]
Disclaimer: I'm by no means an expert with Samsung Internet Browser or the Gear VR version.

Just for others who might be investigating this, there's some useful stuff info I discovered here: http://developer.samsung.com/internet/android/extension-guide

**Comment by AdaRoseCannon** [comment]
The ovrweb:// protocol will open what ever browse the user has set as default which is usually the Occulus browser but can be set to Samsung Internet for GearVR. I am looking for more info into intents.

**Comment by cvan** [comment]
@bluemarvin, colleague and Gecko platform Engineer, might be able to point you in the right direction. He implemented this recently for a special build of Gecko for Android.
