### ISSUE TITLE
Tab crashes if EME is used

### ISSUE THREAD

**Issue by tbutter** [SamsungInternet/support#17]
When keySystemAccess.createMediaKeys() is called the browser tab crashes:

Version 6.2.01.7 BETA

Test case:
https://jsfiddle.net/tz4d707f/

**Comment by poshaughnessy** [comment]
Thank you very much @tbutter for raising this serious issue. Apologies it has taken us so long to reply here. This issue has been raised internally. I hope we will be able to follow up shortly.

**Comment by poshaughnessy** [comment]
This will be fixed for the next minor release, schedule TBC.

**Comment by poshaughnessy** [comment]
I'll close this to keep our issues list to items we still need to address, but I'll comment again if I get further info on the release. Thanks again for raising!
