### ISSUE TITLE
Chrome origin trial support for WebVR

### ISSUE THREAD

**Issue by danrossi** [SamsungInternet/support#19]
Hi there. I spent almost a whole day trying to figure out why WebVR stopped working in GearVR. 

The WebVR flag has been moved to a toggle button in the "Labs" menu. The flags section makes no effect. 

There has been no documentation to support this change. 

Is there a way to support Chrome's origin trial metadata. So enable WebVR on a domain by default ? GearVR kind of needs it enabled by default. It shouldn't have to be user initiated.

**Comment by poshaughnessy** [comment]
Sorry you had such a frustrating time finding the toggle, @danrossi. I was not aware of any change of behaviour with the flags myself. I'm speaking with our colleagues, we'll check about updating our documentation and discuss your request.

**Comment by poshaughnessy** [comment]
Thanks for raising this @danrossi. We've updated the documentation here now:

- https://samsunginter.net/docs/webvr
- https://webvr.rocks/samsung_internet

We don't have plans for an Origin Trial or to enable it by default yet. However, I understand that users should get prompted to enable WebVR if a site uses it and they haven't got it switched on. If that's not working for you, please raise a separate issue with details of the site in question and I'll pass that onto our colleagues!

**Comment by danrossi** [comment]
Hi , the general rule is to check for the existence of 

```
navigator.getVRDisplays
```

Before attempting to use it. Therefore I don't believe there would be such notification correct  ?
