### ISSUE TITLE
Incorrect navigator.onLine with installed web apps

### ISSUE THREAD

**Issue by pierredewilde** [SamsungInternet/support#20]
With both Samsung Internet release version (5.4.02.3) and Beta version (6.2.01.7), `navigator.onLine` works as expected until you install the web app on mobile via `Add to Home screen`.

When the web app is installed on the mobile, `navigator.onLine` does not change when the connection is broken or reestablished.

A possible workaround is to run another instance of `Samsung Internet`browser: in that case, `navigator.onLine` works again as expected.

Tested on Samsung Galaxy A5 2016 with Android 7.0

**Comment by poshaughnessy** [comment]
Thank you for reporting this @pierredewilde. I've raised this internally and we will follow up!

**Comment by pierredewilde** [comment]
window `online` and `offline` events are not fired:
```
window.addEventListener('online', function() {
  console.log('online');
}, true);
window.addEventListener('offline', function() {
  console.log('offline');
}, true);
```
