### ISSUE TITLE
Pretty bad issues going on with SemanticUI with Samsung Internet

### ISSUE THREAD

**Issue by aguyinmontreal** [SamsungInternet/support#21]
Hello! There is some pretty bad issues going on with Samsung Internet and SemanticUI.

Maybe someone from Samsung could give some insight here:

https://github.com/Semantic-Org/Semantic-UI/issues/5515

"Samsung Internet does something interesting with the DOM, and the transition component can’t transition labels (as well as modals—#5341), because they’re “no longer attached to DOM”, even though I could see them in the DOM. Somehow, this might be the cause of crashing reported in #5341, as well as crashes that I’m experiencing while being connected to a PC."

(furthermore, there are also these issues: https://github.com/Semantic-Org/Semantic-UI/issues/5341  and https://github.com/Semantic-Org/Semantic-UI/issues/5514 )

Thank you!

**Comment by aguyinmontreal** [comment]
@poshaughnessy

**Comment by poshaughnessy** [comment]
Thanks @aguyinmontreal. Sorry for the slow follow-up and sorry you've had so many issues. We'll look into them. NB. We are just [releasing v6.2](https://medium.com/samsung-internet-dev/samsung-internet-v6-2-now-stable-ab7f95ed8b4b) with a Chromium engine upgrade, so hopefully this might help with one or more of these issues? I can help test and look into it next week though.

**Comment by aguyinmontreal** [comment]
Thanks @poshaughnessy In the meantime, we were able to find some workarounds:

For issue Semantic-Org/Semantic-UI#5515 , we suggested this pull request: https://github.com/Semantic-Org/Semantic-UI/pull/5915

For issue Semantic-Org/Semantic-UI#5341 , we were able to fix it by replacing `$popup.modal('show');` by `$popup.modal('show', {transition:'fade'});`

For issue  Semantic-Org/Semantic-UI#5514 , we took ronhornbaker's suggestion: `delay : { hide : 300, show : 200, search : 50, touch : 250 }`

Please let me know if you find a better solution for these!

I hope Samsung browser will fix these disparities in the next releases (and not become a new "Internet Explorer" :D )

**Comment by aguyinmontreal** [comment]
@poshaughnessy  If you have a few minutes to give, we have a very odd issue with an old version of the Samsung Browser ( Galaxy S5-Android 4.4.2-SM-G900F-US3 on http://developer.samsung.com/remotetestlab/rtlDeviceList.action#  ) that we can't debug.
