### ISSUE TITLE
navigator.getGamepads() returns wrong hand in GearVR

### ISSUE THREAD

**Issue by vincentfretin** [SamsungInternet/support#22]
With Samsung Internet for Gear VR 5.4.10.4

`navigator.getGamepads()` is returning the wrong hand in GearVR.
When I select left hand in the GearVR system preferences,
`navigator.getGamepads()` returns `hand: "right"`:
![samsung_internet_left_hand](https://user-images.githubusercontent.com/112249/32133819-beb9508a-bbdf-11e7-83eb-cdb790b370e3.png)

When I select right hand in the GearVR system preferences,
`navigator.getGamepads()` returns `hand: "left"` :
![samsung_internet_right_hand](https://user-images.githubusercontent.com/112249/32133815-a446d1fa-bbdf-11e7-9c95-af234d1fa507.png)

This is completely reversed.

For comparison with Oculus browser that has the correct behavior, see
https://github.com/aframevr/aframe/issues/2844#issuecomment-340179000

**Comment by poshaughnessy** [comment]
Thank you @vincentfretin, sorry for the slow follow-up, we'll get back to you on this next week.

**Comment by mkeblx** [comment]
Hi @vincentfretin, this issue has now been fixed for next release. Thanks again.

**Comment by poshaughnessy** [comment]
Hoping we can close this issue now? Anyone able to just confirm it's fixed in the v5.6 release? (I tried a [little test case here](https://poshaughnessy.github.io/gear-vr-gamepads-hand-test/) but I'm not getting any useful output from `navigator.getGamepads()`, not sure why... @mkeblx Might you know where I'm going wrong? :))

**Comment by vincentfretin** [comment]
I confirm this is resolved in the latest version. With aframe, the controller is showing in the left or right hand depending on the system preferences.

**Comment by poshaughnessy** [comment]
Thanks @vincentfretin !
