### ISSUE TITLE
Web Notifications Permission Dialog Implementation concerns

### ISSUE THREAD

**Issue by fabianuribe** [SamsungInternet/support#24]
Hello folks, we are very excited and ready to roll out browser push notifications on Samsung browser, however we have noticed that the current implementation around the permission dialog for Web Notifications might be confusing for the users.

Currently on beta 6.2.017, the Notifications permission dialog provides 3 options:
- DO NOT SHOW AGAIN
- DENY
- ALLOW

The “*DO NOT SHOW AGAIN*” option label doesn't seem to have enough context or be sufficiently descriptive of the actual outcome after selecting it. We are observing that the option has the capacity to disable the Browser Notifications completely for the entire browser instead of addressing a single domain preference, and hence potentially affecting unrelated sites making use of the feature.

#### Hypothetical Scenario:  Site "A" permission status gets affected by site "B" permission dialog

1. User navigates to site "A" and site requests permission to send Notifications.
2. User grants permission to site "A" for receiving Notifications.
3. Happy User is enjoying and engaging with Notifications from site "A".
4. User navigates to site "B" which also requests permission to send Notifications.
5. User is not interested on site "B" Notifications, selects "*DO NOT SHOW AGAIN*" option since user never wants to be prompted **by site "B"** again.
6. Sad User no longer receives Notifications from site "A"

Our main concerns are:

- Given the average user might not be entirely familiar with the Permissions API, and judging by its label, the “*DO NOT SHOW AGAIN*” option seems to be a reasonable option to choose in order to stop getting prompted by a particular site, but it fails to convey the message that the Web Notifications feature will be completely disabled. 
- It also feels very drastic that site "B" has a chance to affect site "A" features.
- The current design on the dialog seems to be optimizing for that outcome given that the "*DO NOT SHOW AGAIN*" occupies the most space making it the most prominent option to select in comparison to the more subtle "*DENY*" option.

**Comment by poshaughnessy** [comment]
Thanks for raising this @fabianuribe. I've notified colleagues and we should speak about this further next week.

**Comment by fabianuribe** [comment]
Thanks for raising it @poshaughnessy, we will be monitoring this thread for any updates from your end.

**Comment by poshaughnessy** [comment]
Hi @fabianuribe. Sorry there's not going to be any immediate updates on this - if we are going to make a change to this behaviour then it would not be before the next major release, v7. However, this request has been passed on to the UX team to review and so we'll see what they say. Thanks again for prompting that.

**Comment by poshaughnessy** [comment]
Hi @fabianuribe, we are intending to change this - by removing the "do not show again" option - for the next major v7 release, in 2018. Thanks again.

**Comment by fabianuribe** [comment]
Thank you @poshaughnessy we will be looking forward to v7 release.
