### ISSUE TITLE
[idea]add the IDs and passwords synchronization with Samsung Cloud

### ISSUE THREAD

**Issue by S3ndG** [SamsungInternet/support#25]
Hi :)
I love your Internet browser but I think there is a big thing that is missing currently : the IDs and the passwords should be synchronized with Samsung Cloud (like the bookmarks).
What do you think about this suggestion?
Thanks for reading.

**Comment by poshaughnessy** [comment]
Hi @S3ndG. Do you mean your website logins? You should be able to store them with Samsung Pass and then they should get synchronized with your other devices that are signed in with your Samsung Cloud account. Is that not working for you?

**Comment by poshaughnessy** [comment]
For reference, here is what we shared about this at the Samsung Developer Conference recently:

![SDC 2017 slide on Samsung Pass sync](https://user-images.githubusercontent.com/151207/32492223-79b1f5da-c3b1-11e7-8900-78c7903f2be7.png)

**Comment by S3ndG** [comment]
That might be a solution for website logins & passwords synchronization but the problem is that the fingerprint captor of my Galaxy A5 (2017) is not working well, it often doesn't recognize my prints.
And Samsung Pass needs that fingerprint to work, isn't it? 

So you could do like Google Chrome that store on the Cloud the logins and passwords without asking the fingerprint... unless the Samsung Pass dev team finds a solution to these identification problems, by adding another method to be identified for instance.

**Comment by S3ndG** [comment]
By the way, may you please tell me where I can make a sugggestion for the developpers of the Samsung Pass app? Is there any github account?
Thank you very much .

**Comment by poshaughnessy** [comment]
See also #27 (closing to merge with this one) - ability to update passwords without using biometrics. I'll check with colleagues!
