### ISSUE TITLE
Rate of denied push/notification permission seems high on Samsung Internet users

### ISSUE THREAD

**Issue by coox** [SamsungInternet/support#28]
Dear Samsung Internet Dev Rel Team,

We have deployed a PWA that takes regularly sends push notifications to users who explicitly granted permission when prompted.

What we noticed is that there seems to be a much higher number of ”denied” permissions for users with a SamsungBrowser user-agent than for all other browsers.

We dug a little, and it seems that the browser version does not particularly matter, but rather, there seems to be a higher proportion of devices where the permissions are denied globally, at browser-level (as opposed to origin-level).

Is this a phenomenon that is known to you? Could it be because of some factory setting let to the appreciation of the device manufacturer, carrier, or another vendor? Is there any way to tell/predict/query, programmatically or otherwise?

We would really appreciate any input or advice on the matter.

Many thanks!

**Comment by poshaughnessy** [comment]
Hi @coox. Apologies that you're running into this. I presume this is to do with this issue: https://github.com/SamsungInternet/support/issues/24 i.e. the permission prompt "do not show again" button logic. We are planning to change this in the next major release, v7. I think this also explains #29?

**Comment by coox** [comment]
Thank you for your reply, @poshaughnessy. It is quite possible indeed that this phenomenon (and perhaps #29) is related to this quite radical UX option.

Do you know since which version this “Do not show again” button has been present in Samsung Internet?
