### ISSUE TITLE
Unicode character support (word joiner)

### ISSUE THREAD

**Issue by poshaughnessy** [SamsungInternet/support#3]
David Corbacho [reported on Twitter](https://twitter.com/dcorbacho/status/827466824950366209) issues with HTML5 entities / Unicode characters, specifically the ['word joiner' character](https://en.wikipedia.org/wiki/Word_joiner).

Testing on S7 Edge, I can see that word joiner (`&#8288;`) is not supported in v4.0 using [this JSFiddle](http://jsfiddle.net/r6yu4tz0/2/):

![nobreak-v4](https://cloud.githubusercontent.com/assets/151207/22980509/a5781b68-f391-11e6-8c0c-e94d227f8ebd.png)

However, on v5.0, it appears to be interpreted correctly:

![nobreak-v5](https://cloud.githubusercontent.com/assets/151207/22980517/a8f631f8-f391-11e6-850a-91f7c36dfc7d.png)

I've glanced through all the characters on the [reference chart](https://dev.w3.org/html5/html-author/charref) but I could not see any other significant differences between v4.0 and v5.0 (except some minor styling changes to a handful).

v4.0 is based on Chromium M44 and v5.0 is based on Chromium M51. I found [a Chromium bug related to this](https://bugs.chromium.org/p/chromium/issues/detail?id=225862), which was apparently fixed in M49. However, it was reported as an issue on Windows only, so I'm not sure it's related.

So hopefully it's fixed already? But David mentioned in [the thread](https://twitter.com/dcorbacho/status/827527070926458884) that it was also unsupported for him in Samsung Internet 5.0 on Android 6. I haven't been able to replicate this yet on my S7 Edge on Android 7.0...

David please could you confirm which device you are using with Samsung Internet 5.0 and how it is displayed there? Thanks!

**Comment by dcorb** [comment]
Thanks for following up the tweet.
It was a friend's phone **Samsung Internet 5.0 on Android 6.** It displayed as an unrecognised character, with the box icon, like your screenshot.

**Comment by poshaughnessy** [comment]
Sorry for being slow on this, @dcorb. I checked on @diekus's phone where I replicated the issue on Samsung Internet v4.0 and verified that it works OK on that device in Chrome. So it certainly seems to be a browser issue, but then again I get a different result to your friend's phone with the same browser (v5.0) on Android 7. I will follow up with engineering colleagues and try to find out the answer!

**Comment by dcorb** [comment]
Thanks for following up. It's quite useful character and is well supported across browsers, so it would be nice you can verify it works, or add tests for it, so there is no regressions in the future

**Comment by poshaughnessy** [comment]
Hi @dcorb. Sorry I didn't manage to figure this out further yet. Now we are [releasing v6](https://medium.com/samsung-internet-dev/samsung-internet-v6-2-now-stable-ab7f95ed8b4b), please might you be able to let me know if you / your friend can still replicate this issue? (It's still working OK for me on my S7). Thanks!

**Comment by poshaughnessy** [comment]
I'm going to close this issue now then, but please re-raise if you still spot it with v6.
