### ISSUE TITLE
Tweet embeds don't work on Samsung internet 6.2

### ISSUE THREAD

**Issue by awebdeveloper** [SamsungInternet/support#30]
I see blank spaces in place of Twitter embeds on sites. I have tried with adblocker disabled too

**Comment by poshaughnessy** [comment]
Hi. I couldn't replicate this at https://dev.twitter.com/web/embedded-tweets (screenshot below).

Please could you provide replication steps? Are there any errors in the console? Thanks!

<img src="https://user-images.githubusercontent.com/151207/34001161-2db23458-e0e7-11e7-8fb2-15ee74eb881e.png" width="300px" alt="Embedded tweet example">

**Comment by awebdeveloper** [comment]
will share soon.

**Comment by awebdeveloper** [comment]
See this https://www.ndtv.com/entertainment/13-years-of-swades-aamir-khan-played-an-important-part-in-shah-rukh-khans-movie-1788865?amp=1&akamai-rum=off

**Comment by awebdeveloper** [comment]
https://imgur.com/a/HYPZW

Notice the blank space in place of a image

**Comment by poshaughnessy** [comment]
I couldn't replicate this with content blocking disabled. Using v6.2 stable. Here's how it looks for me. NB. The blank space from your screenshot appears to be an ad, not a Twitter embed - but I found a Twitter embed below it:

<img src="https://user-images.githubusercontent.com/151207/34101319-4466d520-e3dd-11e7-94c0-7feca75f5582.png" alt="Samsung Internet screenshot" width="300px"/>

One thing just to check, if you tap the menu, does it have an option saying "View without content blocker"? If so, please try tapping that and see if that makes a difference. Thanks!

**Comment by awebdeveloper** [comment]
Tried that. (Without blockers) no use. I am on 6.3.10.3

**Comment by poshaughnessy** [comment]
@awebdeveloper Sorry for the slow follow-up. I'm not sure why I didn't mention the separate, in-built Tracking Blocker as another likely cause before. If you're still having the issue, please could you also try disabling the Tracking Blocker in your Extensions menu, if you have it switched on? That did the trick for Jon over here on Twitter!: https://twitter.com/enolajon/status/979286983339102208
