### ISSUE TITLE
High contrast mode has issues with black icon image

### ISSUE THREAD

**Issue by awebdeveloper** [SamsungInternet/support#31]
Could you apply a CSS filter or invert on images that have a small size and are predominantly black.

**Comment by poshaughnessy** [comment]
Thanks for raising this @awebdeveloper.

I made [a quick test case](https://high-contrast-black-image-test.glitch.me/) and I see what you mean:

<img src="https://user-images.githubusercontent.com/151207/33997489-74720450-e0dc-11e7-8bbd-b253d09376b2.png" width="300px" alt="Screenshot of High Contrast issue"/>

I will check this with my colleagues!

**Comment by awebdeveloper** [comment]
also, High contrast doesn't get applied to PWA's

**Comment by poshaughnessy** [comment]
Oh that's strange, it did get applied for me, tested with the Twitter Lite PWA, launched from home screen, with v6.2 (screenshot below). Please might you be able to write that up as another issue, with some replication steps? Thanks!

<img src="https://user-images.githubusercontent.com/151207/34000291-be9a6970-e0e4-11e7-8d9e-6e5aa4833542.png" alt="Twitter Lite PWA with high contrast" width="300px"/>

**Comment by awebdeveloper** [comment]
I take it back. You are right it works. I dont know why it didnt work earlier but it works fine now.  Thanks

**Comment by poshaughnessy** [comment]
@awebdeveloper Please may I ask a couple more questions. 

In my test case, I replicated it with an SVG image. Is that what you're using too?

Also might you have a real world example you could share a link with us to? That might help us to prioritise the issue appropriately. Thanks!

**Comment by awebdeveloper** [comment]
Try Google keep

**Comment by awebdeveloper** [comment]
PS: I am just a Samsung internet high contrast mode user as far as this issue is concerned. For the simple fact that it saves battery on my amoled Samsung phone

**Comment by poshaughnessy** [comment]
> Try Google keep

Isn't that a native app? I tried to access on the web but it just redirects me to the app...

**Comment by awebdeveloper** [comment]
Then go to setting are remove default open with. It works on web too. Just that keep app on your phone has associated itself with the link

https://outweb.io/1512662908824

**Comment by awebdeveloper** [comment]
Notice the top tabs/menu on  YouTube https://m.youtube.com/feed/trending
