### ISSUE TITLE
Support of `beforeinstallprompt` event

### ISSUE THREAD

**Issue by coox** [SamsungInternet/support#32]
Dear Samsung Internet Dev Rel Team,

We have deployed a PWA that leverages the (non-standard) [beforeinstallprompt](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent) event, in order to fine-control install prompt to the user, more specifically to display it upon button tapping.

Among our usage data, we have noticed that this event seems to be seldom fired from Samsung Internet browser, if ever.

What is Samsung Internet's level of support, or schedule for support, of this event? Is there an alternative mechanism that we should feature-detect and use instead?

Many thanks!

**Comment by dustinbolton** [comment]
The beforeinstallprompt event support is pretty important for progressive web apps to have a user-friendly experience. I strongly add my support in for Samsung Internet to add support for the beforeinstallprompt event in the same way Chrome does.

**Comment by coox** [comment]
It looks like the beforeinstallprompt event is now part of the draft of the Web App Manifest spec:
https://www.w3.org/TR/appmanifest/#beforeinstallpromptevent-interface

The [MDN Browser Compatibility matrix](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent#Browser_compatibility) now reports that Samsung Internet fully supports it, but it is unclear since which version:
https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent

Dear Samsung Internet Dev Rel Team, would you mind confirming this? It would be very beneficial to clarify the level of support, and since which version it has been the case.

**Comment by PicchiKevin** [comment]
see #69 
> > Support for window.addEventListener('beforeinstallprompt', function(){} ) is vital for making progressive web apps user-friendly.
> 
> We have added the support for beforeinstallpromt in Samsung Internet v10.2 - which is currently our latest Beta version. Please let us know if there are more improvements necessary!

**Comment by coox** [comment]
Thank you @PicchiKevin!
