### ISSUE TITLE
Black colour in high contrast mode is #060606

### ISSUE THREAD

**Issue by awebdeveloper** [SamsungInternet/support#34]
Plz change it to #000. This will help conserve battery in amoled screen

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
