### ISSUE TITLE
Device Resolutions in different battery modes

### ISSUE THREAD

**Issue by diekus** [SamsungInternet/support#35]
We are gathering information of devices and their default resolutions during different power modes. Please input the device default setting per power mode.

|Device|Res 1|Res 2|Res 3| Max Power Saving|Medium Power Saving|Performance|
|-------|------|------|-----|---------------------------------|---------------------------|----------------------|
|Note 8   () |1480x720 (HD+)|2220 (FHD+)|2960x1440 (WQHD+)|HD+|HD+|WQHD+|
|S8   () |||||||
|S8+   () |||||||
|S7   (SM-G930) |1280*720(HD)|1920*1080(FHD)|2560*1440(WQHD)|HD|FHD|WQHD|
|S7+   () |||||||
|S6   () |||||||
|S6 Edge   () |||||||
|S6 Edge +   () |||||||
|J2 2017 |||||||
|A8+ 2018  () |||||||
|A8 2018   () |||||||

**Comment by AdaRoseCannon** [comment]
Here are the details for the Note 8:

Resolutions:

1480x720
2220x1080
29601440

Mid powersaving HD+
Max powersaving HD+
Perf: WQHD+
