### ISSUE TITLE
Samsung messages in app browser not loading page

### ISSUE THREAD

**Issue by BroadyCannafo** [SamsungInternet/support#36]
If this isn't the right forum for this question, I would love a pointer to where I can get help with this.

*In the default messages app, it attempts to load in the in app browser.* We have a PWA that when S8 users click the link, it says "This Site Can't Be Reached." If you copy the link and open it directly in the full browser it works fine.

I'm trying to find some sort of resource on what the problem is, and if there is something I can change/eliminate in my app so it will load in the messages in app browser. We deal with 100's of thousands of random users via text to distribute our PWA, so I can't give them instructions to modify their phone default settings or use a different text app.

**Comment by poshaughnessy** [comment]
Hi @BroadyCannafo. Thanks for raising this. 

Is this the use case you're having trouble with - i.e. opening a link within the Messages app on a Samsung phone - but for you, it's not loading in the Custom Tab?:

![Screen recording](https://user-images.githubusercontent.com/151207/35538703-b9f3dd76-0546-11e8-831a-6f7f946c4abe.gif)

If so, please could you share some further details to help us try to replicate it? What device and browser version have you seen this with? Is it possible you can share the URL, or a test case that shows the same issue? Does it work if you tap the menu and select 'Open in Samsung Internet'? 

Thanks!

**Comment by BroadyCannafo** [comment]
Yes, a link is sent through the Messages app.

Phone: Galaxy S8
Messages Version: 4.2.03.20
Carrier: Verizon
Link: https://goo.gl/hdHZoy
Does NOT work when you select Open in Samsung Internet

I have 1 phone I can reproduce this on, and 1 phone that I cannot.
Currently I only have direct access to these two phones, but I know others
have had problems with this. We don't really have a relationship with the
direct users, so we only hear about a fraction of the problems. Thus since
I've heard it twice, it's probably been an issue at least 20 times or more.

[image: Inline image 1][image: Inline image 2]


Joshua Broady
Cannafo.com
541-480-4195
JoshB@Cannafo.com

**Comment by BroadyCannafo** [comment]
Do you run these links through a proxy? If they paste the url into Chrome,
it works for them. Seems like a DNS issue somewhere in the chain. The
problem also happens for either the short URL from Google or the direct
URL. (Direct URL rewards.creativecropsrec.com)


Joshua Broady
Cannafo.com
541-480-4195
JoshB@Cannafo.com

**Comment by BroadyCannafo** [comment]
whatsmybrowser.org/b/5HU6CP7

**Comment by poshaughnessy** [comment]
Thanks for the extra info @BroadyCannafo. I haven't been able to replicate it yet so I'll keep digging... When you said in the original report _"If you copy the link and open it directly in the full browser it works fine."_ did you mean it works in the full Samsung Internet browser, or you meant it just works in Chrome? If it works when you manually copy and paste into the Samsung Internet browser - or when you manually type out the URL in Samsung Internet - that might start leading me to think it's something weird with the way Messages is handling the link?

**Comment by BroadyCannafo** [comment]
It works in Chrome, user reports it does not work by pasting it into
Samsung Internet directly.

I had another user send their whatismybrowser: whatismybrowser.com/w/6G8YJ6G


Joshua Broady
Cannafo.com
541-480-4195
JoshB@Cannafo.com

**Comment by BroadyCannafo** [comment]
Hello, any update on this issue? We are rolling this out to several hundred
thousand users soon. Given that we are seeing this at 50% in our beta test,
it's quite concerning.

If you have the ability to test it based on carrier default profiles, we
have seen the issue with Verizon. Again though, it only happens with some
devices. If you need any further information one of my testers will provide
all the information you could want.

Thanks,


Joshua Broady
Cannafo.com
541-480-4195
JoshB@Cannafo.com

**Comment by sm-g900t3** [comment]
Samsung mobile Email account: esedroopy1@Samsung.com

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
