### ISSUE TITLE
Different colors on the adress bar.

### ISSUE THREAD

**Issue by cyberon** [SamsungInternet/support#38]
The address bar doesn't look very good with all those different tones of gray on the letters.

![screenshot_20180205-140422_samsung internet beta](https://user-images.githubusercontent.com/683597/35809498-c4b9c650-0a80-11e8-8096-4977d0a13cd1.jpg)

**Comment by poshaughnessy** [comment]
Thanks for raising this example @cyberon. It looks like this is related to #15. I'll check on the status for the next release.

**Comment by mph35** [comment]
Hi, do you have a timeframe for the release of v6.4.x please?

**Comment by poshaughnessy** [comment]
Hi @mph35, sorry for the slow follow-up. v6.4 was [released a few weeks ago](https://medium.com/samsung-internet-dev/lets-connect-with-samsung-internet-v6-4-stable-1f197d43a812) (a couple of days after your comment).

The issue with the white text has been resolved now. However, we still have these grey icons. They're also in v7.2 beta. So we'll need to check with the UX team what they advise. Thanks!

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
