### ISSUE TITLE
CustomTabsCallback not reporting some navigation events

### ISSUE THREAD

**Issue by CoderSpinoza** [SamsungInternet/support#39]
I am developing an OAuth login module with custom tabs and currently experiencing an issue with <a href="https://developer.android.com/reference/android/support/customtabs/CustomTabsCallback.html">CustomTabsCallback</a>'s <a href="https://developer.android.com/reference/android/support/customtabs/CustomTabsCallback.html#onNavigationEvent(int, android.os.Bundle)">onNavigationEvent()</a> method on Samsung browser. The issue is that several navigation events are not being reported from the method.
```
    /**
     * Sent when the tab has started loading a page.
     */
    public static final int NAVIGATION_STARTED = 1;

    /**
     * Sent when the tab has finished loading a page.
     */
    public static final int NAVIGATION_FINISHED = 2;

    /**
     * Sent when the tab couldn't finish loading due to a failure.
     */
    public static final int NAVIGATION_FAILED = 3;

    /**
     * Sent when loading was aborted by a user action before it finishes like clicking on a link
     * or refreshing the page.
     */
    public static final int NAVIGATION_ABORTED = 4;

    /**
     * Sent when the tab becomes visible.
     */
    public static final int TAB_SHOWN = 5;

    /**
     * Sent when the tab becomes hidden.
     */
    public static final int TAB_HIDDEN = 6;
```
The documentation specifies 6 navigation events but Samsung internet browser only reports two of them: NAVIGATION_STARTED and NAVIGATION_FINISHED when opened with custom tabs. TAB_SHOWN, TAB_HIDDEN, and NAVIGATION_FAILED are not being called with Samsung browser while they are with Google Chrome.

I was wondering if this is by design, or it is going to be implemented in the near future. I definitely want to support Samsung browser so hope it's the latter :)

p.s. I haven't tested NAVIGATION_ABORTED myself so I am not sure if it is supported or not.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
