### ISSUE TITLE
Adblocker not always active while browsing

### ISSUE THREAD

**Issue by S3ndG** [SamsungInternet/support#40]
Hello!
I'd like to understand why my adblocker (adblock plus) for your browser is not always active.
I sometimes see ads and I must toggle the switch in the preferences to re-enable the adblocker.
(Adblock plus app is in standby but it works despite that in the most of cases.)
Thanks.

**Comment by poshaughnessy** [comment]
Hi @S3ndG, thanks for reporting. I'm not sure, but I hope we can help... Is it that when you go into `Extensions > Content blockers`, you find that Adblock plus is switched off, without you disabling it yourself? Or that it still shows it being switched on, but it's not effective until you switch it off and on again? Do you have any replication steps / examples you could share? Thanks!

**Comment by S3ndG** [comment]
> Or that it still shows it being switched on, but it's not effective until you switch it off and on again?
Yes that's exactly what it happens!
I cannot give any examples, because this issue happens randomly.
The replication steps are just :
- install adblock plus for samsung internet
- put it in standby mode (I personnally have a samsung galaxy A5 2017 phone running android 7.0)
- switch it on in the menu of samsung internet
- browse the web to see if the extension bloks the ads

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
