### ISSUE TITLE
Any plans to support WASM

### ISSUE THREAD

**Issue by PauliusMM** [SamsungInternet/support#41]
Started to develop website with WASM using emscripten and I wanted to test if it works on phone, but it seems Samsung Internet Browser doesn't support it, while Chrome works fine.

Are there any plans to support it in the future?

**Comment by poshaughnessy** [comment]
Hi @PauliusMM, yes we are planning to introduce Web Assembly support and we hope to share an update about it soon...

**Comment by poshaughnessy** [comment]
We're now rolling this out in our Beta channel, as mentioned here: https://medium.com/samsung-internet-dev/new-samsung-internet-beta-introduces-protected-browsing-52f1ce7145f6

I'll close this issue now, but if you come across any problems with it, please open another ticket for us!
