### ISSUE TITLE
React - Field input masking not working on SI browser.

### ISSUE THREAD

**Issue by stephanLeece** [SamsungInternet/support#42]
Hi there. I have a react web app, and i've noticed an issue where input masking on a Field component isn't working.

It's set up so the user is only able to type numbers in the input field, but the user is unable to type any characters at all.

If anyone else has experienced this issue and has a suggestion, please let me know, thanks!

**Comment by poshaughnessy** [comment]
Hi @stephanLeece, apologies for the slow reply. If it's possible you could share a small test case for this, I'd be happy to take a look and see if we can figure out what's happening. Thanks!

**Comment by stephanLeece** [comment]
hi @poshaughnessy, i'm sorry for not updating this. the problem was with a masking package for react i was using. It was structured in a way that meant it didn't work on mobile. 

Problem solved then. Apologies for not closing the issue sooner.

**Comment by poshaughnessy** [comment]
Thanks @stephanLeece, glad you got to the bottom of it!
