### ISSUE TITLE
"Secret mode security" problem.

### ISSUE THREAD

**Issue by abbasfardil** [SamsungInternet/support#43]
Whenever I want to use “Secret mode security” of “Samsung Internet” app in my Galaxy J5 2016 device; it says “Rooting detected. For your security, secret mode can’t be used in rooted phones”. But, my phone is not rooted. I do factory reset to solve this problem. But, it still says “Rooting detected”. Now, how can I solve this problem?

**Comment by poshaughnessy** [comment]
Hi @abbasfardil. Sorry for the slow reply. I had similar problems once before with a phone that I purchased from eBay - it seemed like it had been rooted before I purchased it. But if yours was purchased new and was not rooted, then it seems that there is an issue with the detection. However,  I don't know about that and unfortunately it would be out of scope of the web developer / browser compatibility issues that we try to respond to here. I think the best thing I could recommend would be if you could please try to approach Samsung mobile support in your country of residence / country of purchase? For example for us in the UK we have this support centre site, with various methods of contact: http://www.samsung.com/uk/support/service-centre/ Best wishes and I hope you find a solution!
