### ISSUE TITLE
android.intent.extra.REFERRER not received when deeplinking into an android app

### ISSUE THREAD

**Issue by asafkin** [SamsungInternet/support#44]
I defined an intent-filter http/https schema for an activity inside an android app's AndroidManifest.xml.
This is done in order to deeplink into a specific activity from a browser link.

When im clicking the link from Chrome, and the app is opened, im getting:
getIntent().getParcelableExtra("android.intent.extra.REFERRER") = "https://www....."

When the same link (or any other) is clicked from Samsung browser im getting:
getIntent().getParcelableExtra("android.intent.extra.REFERRER") = null

Can you please advise on this?
Thanks,
Asaf.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
