### ISSUE TITLE
Does not detect the display-mode style

### ISSUE THREAD

**Issue by yucefrizk** [SamsungInternet/support#45]
Hello,

I'm testing a new Web App on a Samsung S8, so I added the below to my css

@media all and (display-mode: standalone) {
  body {
  background-color: #FF0000;
  }
}

the above is working fine on Chrome, however the standalone display-mode style is not detected by Samsung Browser when launching the Web App from the home screen.

I'm using SAMSUNG INTERNET version 6.4.10.5

The manifest file is as below:

{
  "name": "Test Samsung Internet",
  "theme_color": "#9E9E9E",
  "background_color": "#9E9E9E",
  "start_url": "index.html",
  "display": "standalone",
  "orientation": "portrait"
}

**Comment by poshaughnessy** [comment]
Thanks for reporting this @yucefrizk, I've [turned this into a little test case](https://poshaughnessy.github.io/display-mode-standalone-test/) and I can see it is supported in Chrome for Android, but it's not working in either Samsung Internet v6.4 or v7.2 Beta. I'm not sure of the exact state of this spec but it looks to me like we should be supporting it by now. I'll pass it onto our colleagues!

**Comment by shengslogar** [comment]
Is there any update on this? I'm currently experiencing this issue on v7.4.00.70 with Android v8.0.0.

**Comment by evenfrost** [comment]
Any update on this?

**Comment by marcobeierer** [comment]
Does anybody know if there is a reliable method to detect standalone mode in Samsung Internet? It's possible in all other browser I have tested, but haven't found a non-hacky way for Samsung Internet because of this missing feature...

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin

**Comment by alim8j** [comment]
What is the best Samsung laptop for [website design](https://karizmagp.com/wordpress/) and[ SEO](https://karizmagp.com/seo-learn/)?
