### ISSUE TITLE
Live Streaming HLS / WebM

### ISSUE THREAD

**Issue by goldenratio** [SamsungInternet/support#46]
Hi,

I try to play some live streams in Samsung Internet. When I play .webm stream, video is just black but I can hear audio  of the stream (Works in Chrome). When I play HLS.js stream, I see video frames but audio.

Is there any documentation regarding live streaming in Samsung Internet? And any advice on how to solve my problem.

Any help is appreciated. Thanks.

**Comment by goldenratio** [comment]
Note: HLS stream audio is encoded as AAC-LC

**Comment by partyconfetti** [comment]
@goldenratio Did you find any solutions?
