### ISSUE TITLE
Transform: translate3d not working?

### ISSUE THREAD

**Issue by buihoanghai** [SamsungInternet/support#47]
Hi,

I try using: `transform: translate3d(100%, 0, 0);` but seemly it not working at all

**Comment by poshaughnessy** [comment]
Hi @buihoanghai, apologies for not responding sooner.

Please could you share steps to replicate? Which browser version are you using? I tried it out here: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate3d By changing the live demo code to `transform: translate3d(100%, 0, 0);` and it had the same effect for me in Samsung Internet v6.4 as it did in other browsers (the object moved to the right).

**Comment by buihoanghai** [comment]
Thank for response. Due to  my phone using version 2. I just updated to v4. Now its working fine.
