### ISSUE TITLE
Set video src from a Blob

### ISSUE THREAD

**Issue by mlumbroso** [SamsungInternet/support#49]
Hello,

As reported here : https://github.com/muaz-khan/RecordRTC/issues/402
Samsung Internet doesn't seem to support playback of videos when the src is a blob created with new Blob and createObjectURL. Works fine on Chrome Android !
Tested on 6.4 and latest 7.0

You can reproduce using this URL : https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html

Let me know if there are any workarounds that can fix it !

Thanks :)

**Comment by mlumbroso** [comment]
Hi again,
@poshaughnessy any chance you can take a look at this one ?

Thanks !

**Comment by poshaughnessy** [comment]
Hi @mlumbroso, sorry for the slow reply! Thanks for sharing this - yes I can see the issue with the demo you shared. I noticed it works in Opera too, as well as Chrome for Android, but not Samsung Internet. I'm not sure of the cause at the moment, but I will check on this with our engineering colleagues and register an issue internally so we can get this figured out!

**Comment by mlumbroso** [comment]
Hey @poshaughnessy , any news from the team so far ?

Thanks :)

**Comment by poshaughnessy** [comment]
Hi @mlumbroso, apologies again for the slowness! 

I just tried the demo again, but this time I can't get it to work in other browsers either... 

In Chrome for Android (v67, on Android 8.1.0), I could see the camera feed while recording, but it looks like this when I press Stop:

<img src="https://user-images.githubusercontent.com/151207/41033516-cdec9db2-697e-11e8-9355-3a9f0c95c047.png" alt="Chrome screenshot" width="300px"/>

In Opera for Android (v46, on Android 8.1.0), again I could see the camera feed while record, but it looks like this when I press Stop (the play button does not work):

<img src="https://user-images.githubusercontent.com/151207/41033686-547af8e2-697f-11e8-984c-d0129457fc18.png" alt="Opera screenshot" width="300px"/>

Might you know why it could have stopped working for me since last time? Do you know of another small test case we could try out? (If not, I could try to make one!)

**Comment by mlumbroso** [comment]
Hi @poshaughnessy and sorry for the late reply.

On Chrome v67 + 7.1.1 and v67 +8.0.0 it's still working though on my side.
Not sure if specific to your device or not...

I can try to make a test case but probably won't have time to do it before the end of the month.

I'm sure though the developers can have an idea whether there is currently a workaround to support videos where src is a Blob! Any chance to have their opinion on this ? Would be good to know if it's worth the effort to find a solution or if it's plain impossible...

Thanks !

**Comment by mlumbroso** [comment]
Hi @poshaughnessy, any news from the team so far ?
Thanks !

**Comment by mlumbroso** [comment]
Hey @poshaughnessy ,
it's been almost 3 months since I created this issue, is there any way we can handle this faster ? 
Maybe here is not the best place to handle this problem, please advise if we can have a more direct/appropriate way to follow up on this !
Thanks

**Comment by poshaughnessy** [comment]
Apologies @mlumbroso. I spent some time looking into it again myself but I couldn't find a solution yet. I have a ticket open for it in our internal engineering bug reporting system and I will chase it up.

Thanks @AverageMarcus for the test case, by the way! I passed that on 👍

**Comment by poshaughnessy** [comment]
Hi, sorry again for the delay, I just checked on the ticket after getting back from being away. My colleague said that [MSE (Media Source Extensions)](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) needs to be enabled to support a blob URL for a video element's source. Unfortunately, Samsung Internet does not support MSE and I do not have a timeframe for support for it being introduced. (I just checked caniuse and [it looks incorrect there for v6 and v7](https://caniuse.com/#feat=mediasource), so I'll ask / make a PR to get that updated).

My colleague suggested that it would be best to check if the browser supports MSE, before using a blob URL and shared this code:

```
if ('MediaSource' in window && MediaSource.isTypeSupported(mimeCodec)) {
    // MediaSource(MSE) is supported.
    // Blob URL could be set as video source.
} else {
    // MediaSource(MSE) is not supported.
    // Need to implement fallback logic without blob source.
}
```

(I turned this into a [super-simple demo here](https://github.com/poshaughnessy/mse-tests) just to check, it says 'No' in Samsung Internet). 

Would this help to make a workaround for you?

**Comment by mlumbroso** [comment]
Thanks it's helping to start implementing fallback !

Any chance the team has more insights on how to implement the fallback logic ?

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
