### ISSUE TITLE
Side buttons on GearVR don't work as controllers

### ISSUE THREAD

**Issue by nh2** [SamsungInternet/support#50]
Hi,

using `Samsung Internet VR 5.6.00.7` on a Galaxy S7.

I have the GearVR without external hand controllers. I'm trying to use the control cross on the side of the goggles themselves, as shown in the image:

![](https://cdn.arstechnica.net/wp-content/uploads/2015/09/Screen-Shot-2015-09-24-at-10.18.09-AM.png)

When I run `navigator.getGamepads()` in *Samsung Internet*  I get

```
GamepadList {0: undefined, 1: undefined, 2: undefined, 3: undefined, length: 4}
```

and on *Oculus Browser* I get:

```
GamepadList {0: null, 1: null, 2: null, 3: null, length: 4}
```

Is this expected?

How does the SamsungInternet browser expose the side buttons on the GearVR?

**Comment by poshaughnessy** [comment]
Hi @nh2, sorry for the slow reply. The side touchpad is not exposed as a gamepad, but it should be possible to access the 'clicks' and also the swipes, using the touchdown/touchup events. Would that serve your needs?

**Comment by nh2** [comment]
@poshaughnessy Do you know any example site that I could use to test that uses the events you mention?

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
