### ISSUE TITLE
Add Web Share API

### ISSUE THREAD

**Issue by jbmoelker** [SamsungInternet/support#51]
The API is [enabled by default since Chrome 61 for Android](https://developers.google.com/web/updates/2016/09/navigator-share) ([status](https://www.chromestatus.com/feature/5668769141620736)). It's being promoted on popular blogs (like in [Designing for a browserless web on Smashing Magazine](https://www.smashingmagazine.com/2017/11/designing-for-a-browserless-web/#sharing-action)). It's [under consideration in Microsoft Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webshareapi/?q=web%20share%20api) ([related issue](https://github.com/MicrosoftEdge/Status/issues/496)), [under consideration in Webkit](https://webkit.org/status/#feature-web-share), but [no official status from Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1312422) yet.

Since Chrome and Samsung Internet both share a Chromium build, I'm hoping it's quite feasible for Samsung Internet to add the Web Share API.

(I'm requesting this feature here as [suggested by @poshaughnessy](https://twitter.com/poshaughnessy/status/994213390292840448))

**Comment by torgo** [comment]
hi! sorry for the (very) late reply here, but just to note: web share API was made part of 9.2. Web Share Target is aimed to be part of 10.x.
