### ISSUE TITLE
jwplayer hls(.m3u8) video not playing on Samsung Internet

### ISSUE THREAD

**Issue by charutiwari04** [SamsungInternet/support#53]
Hi,
I have a web application which uses jwplayer to play the live stream videos, type of file is hls(HTTP Live STream). The video is playable in all browsers except Samsung Browser. Below are the environment details:

Device: Samsung Galaxy 8
Android Version: 8.0.0
Browser: Samsung Internet
Browser Version: 7.0.0
jwPlayer version: 7 & 8.x
Not sure why is it not playing only on this browser.

Any idea if this could be related to authentication on video? We use http:// for video url but i think it should not stop it from playing.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
