### ISSUE TITLE
Probable Regression Push Notification Payload on V6.4

### ISSUE THREAD

**Issue by fabianuribe** [SamsungInternet/support#54]
It appears there might be a regression introduced on the Push Notifications support for current version of Samsung Internet Browser. 

At least on `6.4.10.5` the Push Notification payload is missing the `data` field, whereas on the Beta version `7.4.00.46` is still working correctly. A quick way to reproduce is to use @gauntface 's simple push demo  (https://gauntface.github.io/simple-push-demo/) and test it by sending a push with some custom message: 

![screenshot_20180612-140206](https://user-images.githubusercontent.com/2894201/41317880-5fb8b872-6e4b-11e8-9477-f6f15a3a404d.png)

When attempting to parse the the `data` field of the Push Notification event, an exception is thrown (`Cannot read property 'json' of null`) which suggests there might be an issue decrypting the payload coming from GCM/FCM.

cc/ @poshaughnessy

**Comment by gauntface** [comment]
It could also be my demo falling out of date or doing something funky, so please feel free to raise issues on simple-push-demo if so.

**Comment by fabianuribe** [comment]
Thanks @gauntface, we are also observing the same behavior on our end, I've decided to reference your awesome demo as quick way to reproduce the issue. I will make sure to open an issue on `simple-push-demo` if it turns out that we are both out of date.

![screenshot_20180612-145730](https://user-images.githubusercontent.com/2894201/41319889-417600d4-6e52-11e8-84f6-e79846778803.png)

> Same "push" event handler works for **Chrome** and **Samsung Internet Browser Beta 7.4**, whereas **Samsung Internet Browser 6.4** is going into fallback mode for Yahoo.com notifications.

**Comment by poshaughnessy** [comment]
Thanks for raising this @fabianuribe, just to let you know that I've shared this with our colleagues and we're going to check on it.

**Comment by poshaughnessy** [comment]
Hi again @fabianuribe. Hopefully some good news for you on this: our new stable release v7.2 is just being rolled out to everyone now over the next few days (we'll be announcing in a blog post early next week). I just checked this issue in v7.2 and thankfully it appears fixed (same as v7.4):

<img src="https://user-images.githubusercontent.com/151207/41497410-b131d52c-714c-11e8-89e7-41808268f398.png" width="400px" alt="v7.2 stable screenshot"/>

**Comment by poshaughnessy** [comment]
Closing as fixed now, but if you spot any further problems then of course please let us know :)
