### ISSUE TITLE
Cannot override pinch-to-zoom gesture

### ISSUE THREAD

**Issue by AshleyScirra** [SamsungInternet/support#57]
It appears the pinch-to-zoom gesture cannot be overridden in Samsung Internet. This breaks our PWA Construct 3 (editor.construct.net).

Repro URL: https://editor.construct.net/#open=ghost-shooter-tut

Wait for it to load then switch to the "Layout 1" tab. This is a WebGL rendered view. When you pinch in this view we block the page scale, and scale the WebGL view instead. This works in Chrome and Safari. However on Samsung Internet it scales the entire page and does not affect the WebGL view scale. The view does not increase in detail and the UI of our PWA at the top disappears offscreen since it's scaling the whole page. This more or less renders our PWA unusable in this view.

Tested with Samsung Internet 7.2.10.33 on a HTC 10 with Android 8.0.

**Comment by AshleyScirra** [comment]
Just tested 7.4.00.53 and looks like it works correctly there. So I guess this is fixed in the next version.

**Comment by poshaughnessy** [comment]
Hi @AshleyScirra, thanks for reporting this. 

I just tried it too and I had a slightly different result: in both v7.2.10.33 and v7.4.00.53, it breaks as you described for me, when the 'Manual zoom' setting is enabled in the Settings menu. (NB. It was OK zooming out, but not zooming in). 

With the 'Manual zoom' option switched off in the Settings menu, it worked as I expected... Is that switched off in your Samsung Internet Beta, perhaps? (Then we might both have the same explanation for the difference?)

I will check this with our colleagues and ask them for further info on this setting.

**Comment by AshleyScirra** [comment]
Yes, turning off "Manual zoom" fixes this in both versions. And you're right - the beta version does still scale the page when pinching. Not sure what happened first time around.

Is the "manual zoom" setting on by default? If so that means this part of our PWA won't work by default. Perhaps it could be off by default instead? I can appreciate the necessity of the feature for accessibility, but it does break the ability to pinch-to-scale a custom view, e.g. the WebGL view in our app. Our PWA is designed to respect the browser default font size and zoom level so that the user can increase the size that way if they have trouble reading content, so there should still be options for users who need to see things larger. The pinch-to-zoom thing is good for document style pages such as news websites, but I suspect forcing that behavior will cause headaches for web apps.
