### ISSUE TITLE
Media Source Extension

### ISSUE THREAD

**Issue by goldenratio** [SamsungInternet/support#58]
Hi,

> Due to compatibility issues, MediaSource Extensions are currently disabled by default in Samsung Internet.

http://docs.w3cub.com/browser_support_tables/mediasource/

Can you update us when will Media Source Extension will be enabled?

**Comment by goldenratio** [comment]
@poshaughnessy  :)

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
