### ISSUE TITLE
cannot install samsung internet version 8

### ISSUE THREAD

**Issue by diehard88** [SamsungInternet/support#59]
the package is blocked.

```
07-19 11:03:38.631  1468  1720 I AASAASKS: list is removed : com.sec.android.app.sbrowser
07-19 11:03:39.867  1468  1720 I AASATokenParser:  advanced hash::f3bf2885bda58ad4ab756072177976b8d7bbce0442fadc7239fa1d2252f9d88d
07-19 11:03:39.900  1468  1720 I AASATokenParser:  AASA_VerifyToken START
07-19 11:03:40.033  1468  1720 I AASATokenParser: index : 1.1
07-19 11:03:40.033  1468  1720 D AASATokenParser: mTokenName : SEC-INF/buildinfo.xml SignerVersion : 
07-19 11:03:40.036  1468  1720 I AASATokenParser: Token is verificated in checkIntegrity!
07-19 11:03:40.039  1468  1720 I AASATokenParser: signerCert is verificated!
07-19 11:03:40.041  1468  1720 I AASATokenParser: CAcert is verificated!
07-19 11:03:40.041  1468  1720 I AASATokenParser: rootCert is verificated!
07-19 11:03:40.042  1468  1720 E AASATokenParser: Violate security policy of MSTG. Package(com.sec.android.app.sbrowser) is blocked  *******. 
07-19 11:03:40.044  1468  1720 I AASAASKS: writeBlockApkList() Success
07-19 11:03:41.296  1468  1720 I AASATokenParser:  advanced hash::f3bf2885bda58ad4ab756072177976b8d7bbce0442fadc7239fa1d2252f9d88d
```

this happens with my s8+, note 8 and tab s3 all running oreo.

thanks!

**Comment by diehard88** [comment]
why is there no mention of version 8 anywhere?

thank you.

**Comment by poshaughnessy** [comment]
It's not released yet. We'll announce when the Beta is available to download (from the Play Store/Galaxy Store) on [our Medium publication](https://medium.com/samsung-internet-dev) and [Twitter account](https://twitter.com/samsunginternet).

**Comment by diehard88** [comment]
Thank you.     

I see that a new version is out.

> <manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="800090100" android:versionName="8.0.00.90" package="com.sec.android.app.sbrowser" platformBuildVersionCode="27" platformBuildVersionName="8.1.0"> 	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27">
