### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by AndreaMonzini** [SamsungInternet/support#6]
Hello,

could you please add clear license for each repository?
For now i saw for example the A-Frame component with MIT license.

I wrote here to not open issues for each repository :)

Thank you.

**Comment by poshaughnessy** [comment]
Thanks @AndreaMonzini.

@AdaRoseEdwards would you mind taking a look at [a-frame-tutorial](https://github.com/SamsungInternet/a-frame-tutorial), [featured-pwas](https://github.com/SamsungInternet/featured-pwas) and [set-sky-box](https://github.com/SamsungInternet/set-skybox)?

@diekus would you mind taking a look at [assets](https://github.com/SamsungInternet/assets),
 [bubble](https://github.com/SamsungInternet/bubble), [loti](https://github.com/SamsungInternet/loti), [pwacman](https://github.com/SamsungInternet/pwacman), [sdevhub](https://github.com/SamsungInternet/sdevhub) and [word-drop](https://github.com/SamsungInternet/word-drop)?

**Comment by poshaughnessy** [comment]
^ Pinging @AdaRoseCannon @diekus

**Comment by poshaughnessy** [comment]
Should be just about all added now. Thanks @AdaRoseCannon @diekus. If there's any specific repos you'd like to check that we're missing, please feel free to open another issue.
