### ISSUE TITLE
Unable to access ID3 meta data from HLS live streams

### ISSUE THREAD

**Issue by goldenratio** [SamsungInternet/support#60]
Hi,

I am unable to access ID3 meta data from HLS live streams. It works fine with Safari and Edge browsers.
Does Samsung browser support it?

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
