### ISSUE TITLE
Samsung Internet Extention

### ISSUE THREAD

**Issue by NikitaAntonenko** [SamsungInternet/support#62]
Hello,

If I want to write extension for Samsung Internet, please could you tell me what kind of API I have to use?

**Comment by poshaughnessy** [comment]
Hi @NikitaAntonenko. There are two kinds of extension possible to develop for Samsung Internet, a 'Content Blocker' extension - for blocking certain content from webpages - and a 'Content Provider' extension - for adding additional popup information based on the context of webpages.

The Extension Development Guide is here on our Samsung Internet developer site:
https://developer.samsung.com/internet/android/extension-guide

For more details or inquiries, you can email browser@samsung.com. Thanks for your interest in developing a Samsung Internet extension.
