### ISSUE TITLE
Html 5 videos not working in Samsung internet browser 

### ISSUE THREAD

**Issue by MohammedLakhani** [SamsungInternet/support#63]
we have used simple video tag to play video in pop for our website stylaaa.com but samsung internet browser doesn't plays it meanwhile it works perfect in chrome or any other browser. @poshaughnessy

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
