### ISSUE TITLE
"Manual Zoom" breaks position: sticky

### ISSUE THREAD

**Issue by williamsdyyz** [SamsungInternet/support#64]
I have a site that is designed as a web app. It uses position:sticky to keep some UI elements attached to the left and top of the screen while other elements are allowed to scroll. (see https://www.tvtv.us/ca/beverly-hills/90210/lu59225D )

The site uses this viewport since everything is designed for mobile:
width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no

Unfortunately, "Manual Zoom" totally breaks the site because the sticky elements don't stick to the edges of the screen. With Manual Zoom turned off, everything works as expected.

It seems to me that Manual Zoom is an accessibility feature and should be OFF by default. As it stands, position:sticky is useless at the page level and users are confused. 

Other browser implementations vary but either work correctly or at least avoid confusing behavior unless the user explicitly requests it:
Opera: Same as Samsung Internet, except Manual Zoom is OFF by default
Firefox: Sticky elements still stick to the edge of the screen- correct behavior I think. Manual Zoom is OFF by default
Chrome: No manual zoom, just respects the viewport setting.

Finally, I can't find any work around that allows my site to work properly on Samsung Internet without the user turning off Manual Zoom, which of course, nobody figures out they need to do.

**Comment by edenprojectde** [comment]
+1 on the Manual Zoom off or rather removed.

**Comment by choisunki** [comment]
I was a bit embarrassed that `user-scalable = no` does not work.
`Manual Zoom` should be disabled by default.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin

**Comment by sayore** [comment]
Yeah sure as if this issue will be handled. Like you did care a lot in the last 2 years for a really unreasonable default setting to change.
This browser literally should not exist in this time and place anymore.

Sorry but this is really tilting me.

EDIT: What i also wanted to say is that i just don't care anymore. I wont go to another site to help you out to get your stuff fixed so GG.
