### ISSUE TITLE
Wand pointer moves eratically when the screen position is changed (Oculus Go).

### ISSUE THREAD

**Issue by ClemsonGIS** [SamsungInternet/support#65]
This issue is in regards to the Oculus Go hardware.  When the screen position is reassigned dramatically from it's default position (ie. perpendicular to the y-axis like when laying in bed) the pointer accuracy is diminished drastically and moving it becomes very erratic.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
