### ISSUE TITLE
can't get profile image from facebook graph api 

### ISSUE THREAD

**Issue by KendoJaaa** [SamsungInternet/support#68]
I can't use facebook graph api
It works on any other browsers except Samsung Internet (the version i'm testing on is 7.4.00.70)
I try to do this
```
        const urlToDownload = `https://graph.facebook.com/v3.1/${
          userDetail.id
        }/picture?type=large`

        const response = await axios({
          method: 'get',
          url: urlToDownload,
          responseType: 'blob'
        })
```
but it always say `Network Error`  without detail. 
Thanks fro the support in advance

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
