### ISSUE TITLE
PWA Home Installation Prompt 조건 문의

### ISSUE THREAD

**Issue by gracefullight** [SamsungInternet/support#69]
ambient-badging 의 조건은

* On HTTPS
* Has a Service Worker Registered
* Has a Web App Manifest
* The Web App Manifest has name or short_name
* The Web App Manifest has start_url
* The Web App Manifest has an icon where size is at least 144x144
* The Web App Manifest has display set to standalone or fullscreen
These requirements may change in later versions of Samsung Internet

로 알고 있습니다.

이 조건을 만족했을 경우 add to home screen install prompt 가 뜨는데요.
설치 되거나 닫을 경우 다시 보여지는 조건이 궁금합니다.

크롬의 경우 설치를 지울 경우 다시금 prompt 가 보여지는데 반해 삼성 브라우저는 a2hs 의 스펙을 알 수 있는 문서가 없네요.

https://developer.samsung.com/internet/android/web-guide 여기의 

> Currently, the notification will show when the user visits a site at least 3 times during a 2 week period. This policy may change.

이 조건은 너무 명시적이지 않은 것 같네요.

**Comment by torgo** [comment]
Picking this up - do we have explicity documentation about the conditions under which the install button & install prompts will show? @diekus

**Comment by dustinbolton** [comment]
Support for window.addEventListener('beforeinstallprompt', function(){} ) is vital for making progressive web apps user-friendly.

**Comment by hjrchung** [comment]
> Support for window.addEventListener('beforeinstallprompt', function(){} ) is vital for making progressive web apps user-friendly.

We have added the support for beforeinstallpromt in Samsung Internet v10.2 - which is currently our latest Beta version. Please let us know if there are more improvements necessary!

**Comment by ghost** [comment]
In Chrome, there is a flag available for developers to bypass the user engagement conditions in order to trigger this event. This is really important when implementing functionality that listens to `beforeinstallprompt`, as otherwise it severely hinders testing. I haven't found any information on there being an equivalent setting in Samsung Internet, have I missed it? Or do you plan adding such a flag?

**Comment by AdaRoseCannon** [comment]
We don't have a flag for that sorry.
