### ISSUE TITLE
Cant enable webVR

### ISSUE THREAD

**Issue by phtester3** [SamsungInternet/support#7]
I went to a web page with VR content
Its was asked to click OK to activate WebVR
I click NOT 
so i could not see the VR Videos
It was sayint go to this web page to activate in your VR : internet://webvr-enable
i went but im redirected to internet://users
and did not activate anything!

**Comment by poshaughnessy** [comment]
Hi @phtester3. Sorry for the slow follow up and difficulty you're having.

Are you still having the same issue?

If so, please could you try enabling it via `internet://flags` (as described [here](https://webvr.rocks/samsung_internet))?

Let me know how it goes. Thanks!

**Comment by poshaughnessy** [comment]
I'll close this issue for now due to inactivity but please feel free to re-open if you need to, @phtester3.
