### ISSUE TITLE
Background-color on Samsung Internet application

### ISSUE THREAD

**Issue by CosminAndrei2000** [SamsungInternet/support#70]
Just finished editing a site, but when I published, the Samsung Internet application do not display `background-color` on `div.`

Everything is displayed correctly in Chrome, only the Samsung Internet encounters this problem. Below I attached 2 screenshots to understand better. Any solution?

HTML : 

`<!DOCTYPE` html>
`<html>`
`<head>`
 `<meta` name="viewport"content="width=device-width, initial-scale=1.0">
`<meta` charset="UTF-8">
 `<title>` Here is title  `</title>`
`</head>`
`<body>`
 `<div` class="paragrafacasa">
  `<p>` Here is my text `</p>`
 `</div>`
`</body>`
`</html>`

CSS : 
`@media` all and (min-width: 360px) and (max-width: 440px) {
`body` {
  background-color:  #4dc6ff;
	}
 	.paragrafacasa {
 		width: 320px;
 		margin-right: auto;
 		margin-left: auto;
 		background-color: #ffffff94;
 		border: 2px solid black;
 		border-radius: 8px;
 		margin-top: 50px;
 	}
 	.paragrafacasa p {
 		font-size: 30px;
 		text-align: center;
 	    }
}

![dul8l](https://user-images.githubusercontent.com/45641485/49546734-9ffc9880-f8e9-11e8-81ed-1f2317ce1109.jpg)
![fldt8](https://user-images.githubusercontent.com/45641485/49546735-9ffc9880-f8e9-11e8-8d56-bfff5caa1d20.jpg)

**Comment by AdaRoseCannon** [comment]
Which version of Samsung Internet are you using? it should be enabled in version 6+ (Chromium 52+)

**Comment by CosminAndrei2000** [comment]
I solved the problem. It was from the addon domain. We had the files on the addon domain and did not display properly.
