### ISSUE TITLE
Android 9: Samsung Internet ignores Private DNS 

### ISSUE THREAD

**Issue by kaischmerer** [SamsungInternet/support#73]
Android 9 supports Private DNS which can be enabled under Settings - Wi-Fi & Internet - Private DNS. With "dns-adguard.com" most advertising and tracking services are filtered. If that option is enabled Browsers should not display any ads. However, this does not apply to Samsung Internet. It seems that the browser ignores the Private DNS setting because it displays ads. Chrome, on the other hand, does not display ads if Adguard's DNS server is set to Private DNS. 

Only if the DNS is manually set to 176.103.130.130 in the Wi-Fi settings of the Wi-Fi router Samsung Internet will no longer display ads.
https://adguard.com/en/blog/adguard-dns-announcement/

**Comment by hwchong** [comment]
I can also confirm that this is happening on a Note 9.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
