### ISSUE TITLE
Support Android Intents for deep-linking URLs in Samsung Internet Browser

### ISSUE THREAD

**Issue by CatGuardian** [SamsungInternet/support#74]
This is a duplicate of #16 on purpose.

This is a super needed feature. Can we please get this implemented?

Basic request is to support the `intent://` javascript protocol as defined here: https://developer.chrome.com/multidevice/android/intents

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
