### ISSUE TITLE
Using window.open(...) Doesn't Work for Non-http and Non-https Protocols

### ISSUE THREAD

**Issue by CatGuardian** [SamsungInternet/support#76]
Hello.

When you try to programatically use window.open(...) with a url that doesn't start with `http://` or `https://`, the samsung browser doesn't actually go to the page specified.

Consider this snippet:

```
    this.$window.open('googlechrome://navigate?url=www.test.com', 'newTabForChromeDeepLink');
```
When this is executed, it should open up the Google Chrome app. But here is what actually happens:

1. If you haven't allowed pop-ups yet for the website that ran this code:

* Then a notification appears saying that a pop-up was blocked with a button that says 'allow pop-ups'. When you click 'allow pop-ups', then it opens up the google chrome app like expected.

2. if you already allowed pop-ups for the website that ran this code:

* Then a new tab is opened up with the 'googlechrome://navigate?url=www.test.com' appearing in the navigation bar but Google Chrome did not open up.

There is a bug here.

Related: #75

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
