### ISSUE TITLE
calling play() on <audio> with src from Blob returns Promise that never resolves

### ISSUE THREAD

**Issue by ckundo** [SamsungInternet/support#78]
Calling `play()` on an audio tag with `src` set to a Blob URL returns a Promise that never completes. This looks like a regression after upgrading to Samsung Internet 8.2, from what we can tell.

```
<audio src="" />

<script>
  function handler() {
    var el = document.querySelector("audio");
    el.load();

    fetch("https://archive.org/download/testmp3testfile/mpthreetest.mp3", {
      method: "get",
    }).then(function (response) {
      return response.blob();
    }).then(function (blob) {
      el.src = URL.createObjectURL(blob);
      return el.play();
    }).then(function () {
      console.log("never resolves");
    }).catch(function (err) {
      console.log("never rejects");
    });
  }

  document.body.addEventListener("click", handler);
</script>
```

^^ example modeled on https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
