### ISSUE TITLE
sms: and mailto: links don't work anymore in webapp (fullscreen) mode

### ISSUE THREAD

**Issue by l3dlp** [SamsungInternet/support#79]
- sms: and mailto: links work in the browser;

- if you use the "add to homescreen" button, they don't work anymore!

- these are basics HTML spec!

**Comment by torgo** [comment]
Thanks – having a look. This isn't intentional as far as I know.

**Comment by l3dlp** [comment]
Thanks for your feedback :)

I stay in tune if needed for any tests.

**Comment by l3dlp** [comment]
Any news ?

### ... that's where open-source proves its power...

I would've been happy to contribute;
for now our users are switching to Chrome or Firefox....

**Comment by hjrchung** [comment]
Hi, afaik the issue has been fixed in v9.2 which is currently released as Samsung Internet Beta and will soon be released in stable.
Thank you for reporting the bug!

**Comment by l3dlp** [comment]
Thanks for your feedback, I know card.pm users who will be happy :)
