### ISSUE TITLE
Feature request: Video player assistant (removed in new update)

### ISSUE THREAD

**Issue by momenabdelkarim** [SamsungInternet/support#80]
Is the removal of the video player assistant in the 9.2 version on purpose or just slated for future release? If it's the latter, is there a timeline on this? It's just about the #1/#2 reason to use the browser.

**Comment by torgo** [comment]
Hi Momen - sorry for the long response time here. We are aware of the issue. The remvoal of the video assistant was an unfortunate outcome of a change of architecture. We're looking to see how we can bring some of the features of video assistant out in a future version. Please keep an eye out on our blog https://medium.com/samsung-internet-dev for updates.
