### ISSUE TITLE
RegEx matching fails after around 10,000 iterations

### ISSUE THREAD

**Issue by astokke** [SamsungInternet/support#82]
We are experiencing an issue where RegEx matching is failing after numerous iterations. 

This only occurs on the Samsung Internet browser, and I have created a [simplified testcase](https://jsfiddle.net/stokke/0oa1bcgn/show) to reproduce this bug. 

Tested on Samsung S9 - Android 9 - Samsung Internet 9.0.01.79. 

Test is passing on Chrome 72.0.3626.121 on the same device. 

Error is triggered on our site https://www.yr.no/en/forecast/graph/2-2950159/Germany/Berlin/Berlin ,
and we are currently working on a workaround for this issue on our end.

Link to testcase: 
https://jsfiddle.net/stokke/0oa1bcgn/show

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
