### ISSUE TITLE
Samsung Internet on Oculus Go consistently, automatically crashes upon launch

### ISSUE THREAD

**Issue by cvan** [SamsungInternet/support#83]
**[Samsung Internet](https://www.oculus.com/experiences/go/849609821813454/)**
version: 5.6.00.10

I uninstalled and reinstalled Samsung Internet on my Oculus Go VR headset.

This didn't seem to happen in earlier versions (last tested ~three weeks ago), but it appears that now, upon a clear refresh, that Samsung Internet on the Oculus Go cannot be launched and automatically, and consistently, crashes while attempting to launch the application.

![image](https://user-images.githubusercontent.com/203725/54191887-073f6100-4474-11e9-8fe0-437818c81d38.png)

![image](https://user-images.githubusercontent.com/203725/54191890-09a1bb00-4474-11e9-930a-3993e12611b9.png)

![image](https://user-images.githubusercontent.com/203725/54191900-0d354200-4474-11e9-82d5-f4bb48c8200d.png)

<hr>

It appears this was encountered by and reported by another user in a review on [the Oculus Store listing](https://www.oculus.com/experiences/go/849609821813454/):

![image](https://user-images.githubusercontent.com/203725/54192037-538aa100-4474-11e9-84f8-7f25a5c1cfc6.png)

<hr>

Any ideas? _(cc: @AdaRoseCannon @mkeblx.)_

**Comment by Metaverse1** [comment]
Hi cvan, I am unable to replicate this event in the SI VR browser on the Oculus Go. Please message me directly so I may learn more about this issue. Thanks!
