### ISSUE TITLE
Videos don't work on Times of India

### ISSUE THREAD

**Issue by awebdeveloper** [SamsungInternet/support#85]
Try playing video in the below link.

https://m.timesofindia.com/videos/entertainment/hindi/akshay-kumar-urges-youth-to-watch-kesari-inspired-by-battle-of-saragarhi/videoshow/68441284.cms

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
