### ISSUE TITLE
Wide lens is picked by default when requesting camera

### ISSUE THREAD

**Issue by pjc0247** [SamsungInternet/support#86]
Occurs in S10

Try this page with S10
https://codepen.io/murtaxa_n/pen/oeYMNm

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
