### ISSUE TITLE
CloseBy support in Samsung Internet v9.x

### ISSUE THREAD

**Issue by robysandre** [SamsungInternet/support#87]
Hi,
is Samsung CloseBy supported from version 9.x onwards?
Reason I am asking is because I don't see the option to enable/disable it in the hamburger menu settings of the Samsung Internet browser after 9.0.0 (released Jan 2019).
Also, I know that Google deprecated Nearby notifications (Dec 6th 2018) so I was wondering if this is related.
I still see CloseBy listed in the feature-set of the browser

https://www.samsung.com/us/support/owners/app/samsung-internet

but when I tried with 9.2.0 version of the browser (default settings) and sending a valid Eddystone URL packet (carrying an https:// -based URI) I don't see any notification happening on the phone.
Can somebody shed some light on what is officially supported, and how CloseBy can be enabled if possible (even after Nearby deprecation)?
Thanks in advance

**Comment by LaszloGombos** [comment]
Hi Roberto. Thanks for your report. CloseBy no longer supported in Samsung Internet 9.x or later versions. We're in the process of updating the documentation.

**Comment by robysandre** [comment]
Ok thanks for the response.
