### ISSUE TITLE
Support appinstalled event

### ISSUE THREAD

**Issue by reyjexter** [SamsungInternet/support#89]
Hopefully this event also gets supported

`window.addEventListener('appinstalled', function(e) {
          
});`

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
