### ISSUE TITLE
Support for CSS Scroll Snap

### ISSUE THREAD

**Issue by StefanKandlbinder** [SamsungInternet/support#91]
Please implement https://www.w3.org/TR/css-scroll-snap-1/.
The browser supported is quite high nowadays https://caniuse.com/#search=scroll%20snap.

Thx - Kind regards
Stefan Kandlbinder

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
