### ISSUE TITLE
No referer in OPTIONS request header for CORS

### ISSUE THREAD

**Issue by realgsong** [SamsungInternet/support#92]
# Repro
1. open https://poclcast.com in samsung browser

browser version: 9.2.10.15 

See attached HAR file. Drag and drop it in chrome dev tool - network tab.

[poclcast.com.har.gz](https://github.com/SamsungInternet/support/files/3255289/poclcast.com.har.gz)

Problem is when requesting OPTION, there's no referer header and it causes failure in security check. this issues is not reproduced with Chrome, Firefox.

# Actual
{"message": "Access was denied to this resource.\n\nRequests from referer <empty> are blocked.\n", "code": "403 Forbidden", "title": "Forbidden"}

No referer value in OPTIONS request header

# Expected
no error.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
