### ISSUE TITLE
Incorrect display with some websites

### ISSUE THREAD

**Issue by S3ndG** [SamsungInternet/support#93]
Hi,
On www.meteofrance.com and www.pagesjaunes.fr, the websites are not displayed correctly 
![Screenshot_1559831070956](https://user-images.githubusercontent.com/14965297/59144163-d53a8e00-89d3-11e9-97dd-7f83cd56fc6c.jpg)
![Screenshot_20190608-095358_Samsung Internet](https://user-images.githubusercontent.com/14965297/59144168-e2577d00-89d3-11e9-8162-4284fec890af.jpg)
These screenshots show what i can see with samsung internet 9.2.10.15 and beta, without any adblocker. 
Can you please fix that ? Thanks. 
Please note that with chrome it works well.

**Comment by AdaRoseCannon** [comment]
Thanks, we'll take a look.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experience this issue I'd recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
