### ISSUE TITLE
Android intent via 307 redirect broken

### ISSUE THREAD

**Issue by jleebranch** [SamsungInternet/support#96]
Hello Samsung Team. I'm from the Branch team (https://branch.io/) and we recently discovered an issue with redirection on the Samsung Browser. Links/redirections are a huge part of our product so it would be great if you could take a look at the following issue with urgency. Thanks!

**Description**
There seems to be a very specific edge case where the Samsung Browser gets stuck on a blank white page. This occurs when you click a link (a link associated with an installed App via Android App Links) in the Samsung Browser. This link is configured to redirect to an Android intent. Because this link is associated with an App that is installed, you will get the 'Open with' dialogue, giving you a choice of Apps to open the link with.

If you click 'Open with' Samsung Internet, the browser opens a blank page but fails to digest the Android intent and launch the App.

Samsung Browser -> Open with -> Samsung Browser -> Stuck on white page

**Video Link:** https://drive.google.com/file/d/12fWkp3uLQiqvYWbjZLldLH4c-EyrsaIg/view?usp=sharing

Android Intent: `intent://explore?adjust_external_click_id=688114382384323057&link_click_id=611345198052001155#Intent;scheme=smulesing;package=com.smule.singandroid;S.market_referrer=link_click_id%3D611345198052001155%26utm_source%3DBranch%26utm_campaign%3D_test%26utm_medium%3Djourneys%26adjust_external_click_id%3D688114382384323057&__branch_flow_type%3Dviewapp%26__branch_flow_id%3D688114382384323057%26__branch_mobile_deepview_type%3D4%26_branch_match_id%3D611345198052001155%26referrer%3Dlink_click_id%253D611345198052001155%2526utm_source%253DBranch%2526utm_campaign%253D_test%2526utm_medium%253Djourneys%26_t%3D611345198052001155%26adjust_campaign%3D_test%26adjust_creative%3Djourneys%26adjust_t%3Dhx6dr4q;S.branch_data=%7B%22%24og_title%22%3A%22Smule%20-%20Connecting%20the%20world%20through%20music%22%2C%22%24deeplink_path%22%3A%22explore%22%2C%22~creation_source%22%3A5%2C%22~view_name%22%3A%22EngineeringTest%22%2C%22android_tracker_id%22%3A%225fi80yi%22%2C%22%24og_description%22%3A%22Smule%20develops%20music-making%20apps%20that%20connect%20people%3A%20Smule%2C%20AutoRap%2C%20Magic%20Piano%2C%20Guitar!%2C%20I%20Am%20T-Pain%2C%20Ocarina%2C%20and%20more%E2%80%A6%22%2C%22~journey_id%22%3A%22_test%22%2C%22adjust_campaign%22%3A%22_test%22%2C%22%24uri_redirect_mode%22%3A1%2C%22%24og_image_url%22%3A%22https%3A%2F%2Fw1.tc.smule.com%2Fassets%2Ficons%2Ffacebook_share-9be2d7093a7a5dbbf9784f28a97cb4fe.jpg%22%2C%22adjust_t%22%3A%22hx6dr4q%22%2C%22~feature%22%3A%22journeys%22%2C%22_branch_match_id%22%3A%22611345198052001155%22%2C%22~view_id%22%3A%22684295815622498305%22%2C%22%2Burl%22%3A%22https%3A%2F%2Flink.smule.com%2FGr1PBQ6fIY%3F_branch_match_id%3D611345198052001155%26referrer%3Dlink_click_id%25253D611345198052001155%252526utm_source%25253DBranch%252526utm_campaign%25253D_test%252526utm_medium%25253Djourneys%26adjust_campaign%3D_test%26adjust_creative%3Djourneys%26adjust_t%3Dhx6dr4q%22%2C%22referrer%22%3A%22link_click_id%253D611345198052001155%2526utm_source%253DBranch%2526utm_campaign%253D_test%2526utm_medium%253Djourneys%22%2C%22~tags%22%3A%5B%22EngineeringTest%22%5D%2C%22~journey_name%22%3A%22_test%22%2C%22%24one_time_use%22%3Afalse%2C%22~id%22%3A%22684298832276275258%22%2C%22~campaign%22%3A%22_test%22%2C%22%24canonical_url%22%3A%22https%3A%2F%2Fwww.smule.com%2F%3F_branch_view_id%3D684295815622498305%22%2C%22ios_tracker_id%22%3A%2262h2jrx%22%2C%22adjust_creative%22%3A%22journeys%22%2C%22%2Bdomain%22%3A%22smule.app.link%22%2C%22%2Bclick_timestamp%22%3A1565297479%2C%22%2Bclicked_branch_link%22%3Atrue%2C%22%2Bmatch_guaranteed%22%3Atrue%2C%22%2Bis_first_session%22%3Afalse%7D;B.branch_intent=true;end`

I will be using the 'Smule' App to reproduce this.
**Steps to Reproduce**
1. Download the Smule App. https://play.google.com/store/apps/details?id=com.smule.singandroid&hl=en_US
2. Open https://jleebranch.github.io/samsungbrowserbug.html in the Samsung Browser. This test page contains a link that is associated with the Smule App. As a result, you will get the 'Open with' dialogue asking you choose the Smule App or Samsung Browser. 
3. If you click Samsung Browser, the link will open in a Samsung Browser tab but be stuck on a blank page. 
4. This does not occur if you click the link from Chrome -> Samsung Browser. Only when you click the link in Samsung Browser and open with Samsung Browser.

**Test Device/Browser Info**
1. Samsung Browser v. 9.4.00.45
2. Device: Galaxy S9

**Notes**
1. Clicking the Android intent above directly from Samsung Browser works fine.

**Questions**
1. Is this the expected behavior?
2. Does Samsung browser not support Android intent redirects?

**Comment by PicchiKevin** [comment]
Hi @jleebranch,
Thank you very much for the complete bug report. A fix has been scheduled for v10.2.

I also have a **good news** for you, v10.2 is already available on the beta app that you can download by using this link: https://galaxy.store/InternetBeta

Thank you & Have fun
