### ISSUE TITLE
Close the browser easily.

### ISSUE THREAD

**Issue by Adrymate9** [SamsungInternet/support#97]
I would like to improve the way to close the browser. 

Currently the way to close the browser when several tabs are open is in the menu of tabs click on the 3 points in the upper left margin Then in the pop-up menu, it says "close all tabs" and then close the browser.

This seems bad to me because of the various steps to close it, besides being in an awkward position for large screen phones. 

I suggest a "close browser" button at the bottom between "new incognito tab" and "new tab".  Or maybe in the main menu a close browser button. Always keep in mind that "close browser" will close all tabs and exit the application.

I hope you can attend my request.

**Comment by PicchiKevin** [comment]
Hi,
Thank you for opening this issue.
We are currently migrating our support channel to the [Samsung Developer Forum](https://forum.developer.samsung.com/c/samsung-internet/).
If you are still experiencing this issue I'd highly recommend re-opening it here please https://forum.developer.samsung.com/c/samsung-internet/

Thanks again,
-Kevin
