### ISSUE TITLE
Can't paste anything in the forms

### ISSUE THREAD

**Issue by S3ndG** [SamsungInternet/support#98]
With the latest stable version of Samsung internet (10.2.00.53), i cant paste some text in a form. Could you please fix that ? Thanks.

**Comment by PicchiKevin** [comment]
Hi @S3ndG ,

Just tried it on my phone (Samsung Internet 10.2.00.53), and it's working.
Could you send me a link where the problem is occurring please ?

**Comment by S3ndG** [comment]
Hi, now it's working again... (?) I don't understand.
On the webpage https://www.caisse-epargne.fr/particuliers  > menu at the top right > accès aux comptes, I couldn't paste my ID. But now, it's working. I will come back here if the issue still occurs. See you.

**Comment by PicchiKevin** [comment]
Feel free to reopen the issue if it happens again.

**Comment by S3ndG** [comment]
This not works well (sometimes I can paste, sometimes not).
Try it on the website I mentionned above - you may have the same behaviour.
